# Generated by Django 5.1.7 on 2025-03-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_monthly_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_daily_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('dayparting_start', models.TimeField(blank=True, null=True)),
                ('dayparting_end', models.TimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.brand')),
            ],
        ),
    ]
